# Generated by Django 4.2.6 on 2023-11-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, max_length=5),
        ),
        migrations.AlterField(
            model_name='driver',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_user',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='photo'),
        ),
    ]
